version: '3.9'
services:
  mongo_db:
    container_name: mongo_69910
    image: mongo:latest
    ports:
      - 27018:27017
  
  api:
    container_name: api_69910
    build: .
    ports:
      - 8081:8080
    environment:
      MONGO_URI: mongodb://mongo_db:27017/coder69910